name: My Dart Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dart
      uses: dart-lang/setup-dart@v1

    - name: Set up environment variables
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Build and test the project
      run: |
        dart pub get
        dart test
